title = "xyztesting website"
baseURL = "https://microelectro.de"

theme = "ananke"
contentDir = "content"
defaultContentLanguage = "en"

SectionPagesMenu = "main"
enableRobotsTXT = true

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "xyztesting website"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2

##########################
# Privacy-related features
##########################
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
